### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by awschristou** [awslabs/aws-lambda-builders#144] opened 2019-12-16 18:43 UTC
**Description:**

Guard against unexpected values when checking the pip version.

Code Location: https://github.com/awslabs/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/python_pip/compat.py#L15

**Expected Behavior**

More user friendly output message

**Motivation**

When running `sam build` commands with the SAM CLI, this is a confusing error to come up against.

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Mac and Linux, using pyenv to set up multiple versions (2.7, 3.6, 3.7, 3.8) of python for development and testing.

**Comment by jfuss** [comment] 2019-12-16 22:04
Duplicate of #135 

Closing

**Closed by jfuss** 2019-12-16 22:04 UTC
